### ISSUE TITLE
Aframe using lots of memory.

### ISSUE THREAD

**Issue by itsakt** [aframevr/aframe-react#83]
CODE: [https://github.com/itsakt/aframe-react-test](url)

[App.js](https://github.com/itsakt/aframe-react-test/blob/master/src/App.js)

**Memory Usage**
This sample code contains five 360 degree images. ( ~600KB - ~1.8MB, 8192x4096 )

**Initial memory usage:**
Google Chrome
![chrome initial](https://github.com/itsakt/aframe-react-test/raw/master/screenshots/cm1.png)

Firefox Developer Edition
![ff initial](https://github.com/itsakt/aframe-react-test/raw/master/screenshots/fm1.png)

**After switching through five images**
Google Chrome
![chrome after five](https://github.com/itsakt/aframe-react-test/raw/master/screenshots/cm2.png)

Firefox Developer Edition
![ff after five](https://github.com/itsakt/aframe-react-test/raw/master/screenshots/fm2.png)

My actual project has 24 images

**After switching through 24 images**
Google Chrome after 20 images (chrome tab crashed after that)
![chrome after 24](https://github.com/itsakt/aframe-react-test/raw/master/screenshots/cm3.png)

Firefox Developer Edition after 24 images.
![ff after 24](https://github.com/itsakt/aframe-react-test/raw/master/screenshots/fm3.png)

**EDIT: Memory usage also increases if I reload the page.**

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/issues/2166

http://stackoverflow.com/questions/42427327/how-to-deallocate-texture-from-memory-in-a-frame

**Comment by cvan** [comment]
@ngokevin you cool with me adding a link to the StackOverflow answer (and/or this issue) to https://aframe.io/docs/0.5.0/introduction/best-practices.html#performance (and/or the FAQ)?

**Comment by ngokevin** [comment]
Was fixed recently https://github.com/aframevr/aframe/pull/2686

**Comment by cvan** [comment]
awesome, thanks 👍
