### ISSUE TITLE
a-collada-model - model does not appear

### ISSUE THREAD

**Issue by anton6** [aframevr/aframe-react#87]
I'm trying to run the "Anime UI" example from aframe on aframe-react, but I'm unable to load engine.dae. It just does not appear.

My Scene contains the following code:
```
<a-assets>
  <a-asset-item id="engine" src="models/engine.dae" />
</a-assets>

<Entity primitive="a-entity" position="1.75 0 1.2" rotation="0 28 0">
  <Entity primitive="a-camera" near="0.1" user-height="0" />
</Entity>

<Entity primitive="a-entity" position="0 0 -3">
  <Entity primitive="a-collada-model" src="#engine" rotation="90 0 0" scale="18 18 18" />
</Entity>
```

Can anyone please tell me what I'm doing wrong and why the model is not appearing.

Thanks!

**Comment by ngokevin** [comment]
Does `<Entity collada-model={{src: '#engine'}} rotation="90 0 0" scale="18 18 18"/>` work?

**Comment by anton6** [comment]
Sorry still did not work.

This is my project structure right now:
<img width="197" alt="screen shot 2017-05-19 at 00 13 33" src="https://cloud.githubusercontent.com/assets/16119505/26227083/151faa6a-3c28-11e7-9018-7cd3e4d7074e.png">



This is what **a-collada-model** looks like when I inspect it:
<img width="1043" alt="screen shot 2017-05-19 at 00 08 43" src="https://cloud.githubusercontent.com/assets/16119505/26226979/6ac0fc90-3c27-11e7-99ca-42ca46072e6f.png">

And when I run the example on aframe I get this:
<img width="1045" alt="screen shot 2017-05-19 at 00 11 09" src="https://cloud.githubusercontent.com/assets/16119505/26227047/c694ddca-3c27-11e7-8691-bbc8e4d9ac3d.png">

**Comment by ngokevin** [comment]
Does the model load OK? 200, 404?

**Comment by anton6** [comment]
Yes the model seems to load OK, 200.

Although, the model appears to load twice for some reason.

This is the log and network tab when page loads:
<img width="573" alt="screen shot 2017-05-19 at 00 33 16" src="https://cloud.githubusercontent.com/assets/16119505/26227675/e822b670-3c2b-11e7-9dd0-d789310e69a3.png">
<img width="688" alt="screen shot 2017-05-19 at 00 36 09" src="https://cloud.githubusercontent.com/assets/16119505/26227681/ef1fa2d0-3c2b-11e7-8dbb-65a445518501.png">

**Comment by ngokevin** [comment]
Hmm, can you inspect what the engine.dae response is? That `nodes` parse error seems to be it, makes it sound like it got something weird in return,

**Comment by anton6** [comment]
Yes, I think you are absolutely correct.
The response does not look right. 

This is the response:
<img width="773" alt="screen shot 2017-05-19 at 00 54 14" src="https://cloud.githubusercontent.com/assets/16119505/26227972/c4a3d7d6-3c2d-11e7-8deb-e43a66b28112.png">

Any idea why this might be?

**Comment by ngokevin** [comment]
Hm, maybe something to do with the dev server? If you open the file, it looks correct, right?

**Comment by anton6** [comment]
Ye, the file looks okay and comes up as expected in the preview window. I copied it over directly from the aframe example.

<img width="766" alt="screen shot 2017-05-19 at 01 55 24" src="https://cloud.githubusercontent.com/assets/16119505/26229024/6d366834-3c36-11e7-9a61-d97409d9b232.png">

By the way I'm using the **aframe-react-boilerplate** for this.
I simply did **npm i** and then **npm start**.

Did I have to configure anything else in the boilerplate for this example to work?

**Comment by ngokevin** [comment]
Try moving the model folder relative to the index.html file?

**Comment by anton6** [comment]
Thanks for pointing me in the right direction. Turns out I just had to put the models folder into public folder.

**Comment by 0O7** [comment]
This post just save me. Had the same issue.
